# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationWorksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('acres', models.DecimalField(decimal_places=2, max_digits=20)),
                ('zone', models.CharField(choices=[('A-R', 'Agricultural Rural'), ('A-B', 'Agricultural Buffer'), ('A-N', 'Agricultural Natural Areas'), ('A-U', 'Agricultural Urban'), ('R-1A', 'Single Family Residential'), ('R-1B', 'Single Family Residential'), ('R-1C', 'Single Family Residential'), ('R-1D', 'Single Family Residential'), ('R-1E', 'Single Family Residential'), ('R-1T', 'Townhouse Residential'), ('R-2', 'Two-Family Residential'), ('R-3', 'Planned Neighborhood Residential'), ('R-4', 'High Density Apartment'), ('R-5', 'High Rise Apartment'), ('P-1', 'Professional Office'), ('B-1', 'Neighborhood Business'), ('B-2', 'Downtown Business'), ('B-2A', 'Downtown Frame Business'), ('B-2B', 'Lexington Center Business'), ('B-3', 'Highway Service Business'), ('B-4', 'Wholesale and Warehouse Business'), ('I-1', 'Light Industrial'), ('I-2', 'Heavy Industrial'), ('P-2', 'Office, Industry, and Research Park')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('lot_number', models.CharField(max_length=100)),
                ('permit_id', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('address_number', models.IntegerField()),
                ('address_direction', models.CharField(max_length=50)),
                ('address_street', models.CharField(max_length=200)),
                ('address_suffix', models.CharField(max_length=100)),
                ('address_unit', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('address_state', models.CharField(max_length=50)),
                ('address_zip', models.CharField(max_length=10)),
                ('address_full', models.CharField(max_length=300)),
                ('dues_roads_dev', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dues_roads_own', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dues_sewer_trans_dev', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dues_sewer_trans_own', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dues_sewer_cap_dev', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dues_sewer_cap_own', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dues_parks_dev', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dues_parks_own', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dues_storm_dev', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dues_storm_own', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dues_open_space_dev', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dues_open_space_own', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('paid_by', models.CharField(max_length=100)),
                ('paid_by_type', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
                ('check_number', models.IntegerField()),
                ('credit_source', models.CharField(max_length=100)),
                ('credit_account', models.CharField(max_length=100)),
                ('paid_roads', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_sewer_trans', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_sewer_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_parks', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_storm', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_open_space', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='plats.Lot')),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_recorded', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('total_acreage', models.DecimalField(decimal_places=3, max_digits=20)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('plat_type', models.CharField(max_length=200)),
                ('expansion_area', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=200)),
                ('block', models.CharField(max_length=200)),
                ('buildable_lots', models.CharField(max_length=200)),
                ('non_buildable_lots', models.CharField(max_length=200)),
                ('cabinet', models.CharField(max_length=200)),
                ('slide', models.CharField(max_length=200)),
                ('calculation_note', models.TextField()),
                ('sewer_due', models.DecimalField(decimal_places=2, max_digits=20)),
                ('non_sewer_due', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlatZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('zone', models.CharField(choices=[('A-R', 'Agricultural Rural'), ('A-B', 'Agricultural Buffer'), ('A-N', 'Agricultural Natural Areas'), ('A-U', 'Agricultural Urban'), ('R-1A', 'Single Family Residential'), ('R-1B', 'Single Family Residential'), ('R-1C', 'Single Family Residential'), ('R-1D', 'Single Family Residential'), ('R-1E', 'Single Family Residential'), ('R-1T', 'Townhouse Residential'), ('R-2', 'Two-Family Residential'), ('R-3', 'Planned Neighborhood Residential'), ('R-4', 'High Density Apartment'), ('R-5', 'High Rise Apartment'), ('P-1', 'Professional Office'), ('B-1', 'Neighborhood Business'), ('B-2', 'Downtown Business'), ('B-2A', 'Downtown Frame Business'), ('B-2B', 'Lexington Center Business'), ('B-3', 'Highway Service Business'), ('B-4', 'Wholesale and Warehouse Business'), ('I-1', 'Light Industrial'), ('I-2', 'Heavy Industrial'), ('P-2', 'Office, Industry, and Research Park')], max_length=100)),
                ('acres', models.DecimalField(decimal_places=2, max_digits=20)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plat_zone', to='plats.Plat')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('gross_acreage', models.DecimalField(decimal_places=3, max_digits=20)),
                ('number_allowed_lots', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='plat',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plat', to='plats.Subdivision'),
        ),
        migrations.AddField(
            model_name='lot',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot', to='plats.Plat'),
        ),
    ]
