# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='parcel_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
