# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lot_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='lot',
            name='address_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='address_suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='address_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
