# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0007_auto_20170706_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubdivision',
            name='number_allowed_lots',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='number_allowed_lots',
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='address_city',
            field=models.CharField(default='Lexington', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='address_state',
            field=models.CharField(choices=[('AK', 'Alaska'), ('AL', 'Alabama'), ('AR', 'Arkansas'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('ME', 'Maine'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('MP', 'Northern Mariana Islands'), ('MS', 'Mississippi'), ('MT', 'Montana'), ('NA', 'National'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NE', 'Nebraska'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('NY', 'New York'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('VT', 'Vermont'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WV', 'West Virginia'), ('WY', 'Wyoming')], default='KY', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='address_zip',
            field=models.CharField(choices=[('40515', '40515'), ('40509', '40509'), ('40516', '40516'), ('40511', '40511'), ('40505', '40505')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='permit_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplat',
            name='expansion_area',
            field=models.CharField(choices=[('EA-1', 'EA-1'), ('EA-2A', 'EA-2A'), ('EA-2B', 'EA-2B'), ('EA-2C', 'EA-2C'), ('EA-3', 'EA-3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalplat',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplat',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplat',
            name='plat_type',
            field=models.CharField(choices=[('PLAT', 'Final Record Plat'), ('DEVELOPMENT_PLAN', 'Final Development Plan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalplat',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='address_city',
            field=models.CharField(default='Lexington', max_length=100),
        ),
        migrations.AlterField(
            model_name='lot',
            name='address_state',
            field=models.CharField(choices=[('AK', 'Alaska'), ('AL', 'Alabama'), ('AR', 'Arkansas'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('ME', 'Maine'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('MP', 'Northern Mariana Islands'), ('MS', 'Mississippi'), ('MT', 'Montana'), ('NA', 'National'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NE', 'Nebraska'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('NY', 'New York'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('VT', 'Vermont'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WV', 'West Virginia'), ('WY', 'Wyoming')], default='KY', max_length=50),
        ),
        migrations.AlterField(
            model_name='lot',
            name='address_zip',
            field=models.CharField(choices=[('40515', '40515'), ('40509', '40509'), ('40516', '40516'), ('40511', '40511'), ('40505', '40505')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lot',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='permit_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='expansion_area',
            field=models.CharField(choices=[('EA-1', 'EA-1'), ('EA-2A', 'EA-2A'), ('EA-2B', 'EA-2B'), ('EA-2C', 'EA-2C'), ('EA-3', 'EA-3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='plat',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='plat_type',
            field=models.CharField(choices=[('PLAT', 'Final Record Plat'), ('DEVELOPMENT_PLAN', 'Final Development Plan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='plat',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
