# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-12 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181210_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approval_required',
            field=models.BooleanField(default=False),
        ),
    ]
