# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-10-02 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191028_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountledger',
            name='original_account_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_ledger_copies', to='accounts.AccountLedger'),
        ),
        migrations.AddField(
            model_name='accountledger',
            name='reconciliation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountledger',
            name='reconciliation_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalaccountledger',
            name='original_account_ledger',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.AccountLedger'),
        ),
        migrations.AddField(
            model_name='historicalaccountledger',
            name='reconciliation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaccountledger',
            name='reconciliation_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
