# Generated by Django 5.2.8 on 2025-11-26 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20251002_1338'),
        ('plats', '0007_auto_20220307_1513'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalaccount',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical account', 'verbose_name_plural': 'historical accounts'},
        ),
        migrations.AlterModelOptions(
            name='historicalaccountledger',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical account ledger', 'verbose_name_plural': 'historical account ledgers'},
        ),
        migrations.AlterModelOptions(
            name='historicalagreement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical agreement', 'verbose_name_plural': 'historical agreements'},
        ),
        migrations.AlterModelOptions(
            name='historicalpayment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical payment', 'verbose_name_plural': 'historical payments'},
        ),
        migrations.AlterModelOptions(
            name='historicalproject',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project', 'verbose_name_plural': 'historical projects'},
        ),
        migrations.AlterModelOptions(
            name='historicalprojectcostestimate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project cost estimate', 'verbose_name_plural': 'historical project cost estimates'},
        ),
        migrations.AlterField(
            model_name='account',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='account_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_account_from', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='account_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_account_to', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='accounts.agreement'),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_lot', to='plats.lot'),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalaccountledger',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalagreement',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprojectcostestimate',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='credit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_account', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='credit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_source', to='accounts.agreement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='plats.lot'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='agreement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='accounts.agreement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcostestimate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_cost_estimate_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcostestimate',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_cost_estimate_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcostestimate',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_cost_estimate', to='accounts.project'),
        ),
    ]
