# -- FILE: pytest.ini (or tox.ini)
[pytest]
addopts = --ds=config.settings.test --reuse-db
; python_files = tests.py test_*.py *_tests.py
filterwarnings =
    ignore::django.utils.deprecation.RemovedInDjango20Warning
    ignore::django.utils.deprecation.RemovedInDjango21Warning
