# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-01-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplat',
            name='cabinet_slide',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plat',
            name='cabinet_slide',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplat',
            name='cabinet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalplat',
            name='slide',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plat',
            name='cabinet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plat',
            name='slide',
            field=models.CharField(max_length=100),
        ),
    ]
