# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-03 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0003_auto_20201202_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplatzone',
            name='acres',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicalsubdivision',
            name='gross_acreage',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='platzone',
            name='acres',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='gross_acreage',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
