# Generated by Django 5.2.8 on 2025-11-26 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_historicalaccount_options_and_more'),
        ('plats', '0007_auto_20220307_1513'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcalculationworksheet',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical calculation worksheet', 'verbose_name_plural': 'historical calculation worksheets'},
        ),
        migrations.AlterModelOptions(
            name='historicallot',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical lot', 'verbose_name_plural': 'historical lots'},
        ),
        migrations.AlterModelOptions(
            name='historicalplat',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical plat', 'verbose_name_plural': 'historical plats'},
        ),
        migrations.AlterModelOptions(
            name='historicalplatzone',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical plat zone', 'verbose_name_plural': 'historical plat zones'},
        ),
        migrations.AlterModelOptions(
            name='historicalsubdivision',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical subdivision', 'verbose_name_plural': 'historical subdivisions'},
        ),
        migrations.AlterField(
            model_name='historicalcalculationworksheet',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalplat',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalplatzone',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsubdivision',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lot_account', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lot',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lot',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot', to='plats.plat'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plat_account', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='amended_parent_plat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plat_amend', to='plats.plat'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plat_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plat',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plat_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plat',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plat', to='plats.subdivision'),
        ),
        migrations.AlterField(
            model_name='platzone',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plat_zone_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platzone',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plat_zone_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platzone',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plat_zone', to='plats.plat'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subdivision_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subdivision_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
