# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('account_name', models.CharField(max_length=200)),
                ('contact_first_name', models.CharField(max_length=100)),
                ('contact_last_name', models.CharField(max_length=100)),
                ('contact_full_name', models.CharField(max_length=200)),
                ('address_city', models.CharField(max_length=100)),
                ('address_state', models.CharField(max_length=50)),
                ('address_zip', models.CharField(max_length=10)),
                ('address_full', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('entry_type', models.CharField(max_length=200)),
                ('non_sewer_credits', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sewer_credits', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_account_from', to='accounts.Account')),
                ('account_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_account_to', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_executed', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('resolution_number', models.CharField(max_length=100)),
                ('expansion_area', models.CharField(max_length=100)),
                ('agreement_type', models.CharField(max_length=100)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='accounts.Account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('expansion_area', models.CharField(max_length=100)),
                ('project_category', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('project_status', models.CharField(max_length=200)),
                ('status_date', models.DateField()),
                ('agreement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='accounts.Agreement')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCostEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('estimate_type', models.CharField(max_length=200)),
                ('land_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('design_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('construction_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('admin_cont', models.DecimalField(decimal_places=2, max_digits=20)),
                ('management_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('credits_available', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_cost_estimate_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_cost_estimate_modified', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_cost_estimate', to='accounts.Project')),
            ],
        ),
        migrations.AddField(
            model_name='accountledger',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='accounts.Agreement'),
        ),
        migrations.AddField(
            model_name='accountledger',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountledger',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_lot', to='plats.Lot'),
        ),
        migrations.AddField(
            model_name='accountledger',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
