# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 21:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plats', '0002_auto_20170614_1700'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('paid_by', models.CharField(max_length=100)),
                ('paid_by_type', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
                ('check_number', models.IntegerField()),
                ('paid_roads', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_sewer_trans', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_sewer_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_parks', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_storm', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_open_space', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_created', to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_account', to='accounts.Account')),
                ('credit_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_source', to='accounts.Agreement')),
                ('lot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='plats.Lot')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
