# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountledger',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='accounts.Agreement'),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='account_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_account_from', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='account_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_account_to', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_lot', to='plats.Lot'),
        ),
    ]
