# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-02 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0002_auto_20200114_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplat',
            name='right_of_way_acreage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplat',
            name='total_acreage',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='plat',
            name='right_of_way_acreage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='total_acreage',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
