# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0004_auto_20170629_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationworksheet',
            name='name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcalculationworksheet',
            name='name',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='dues_open_space_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='dues_open_space_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='dues_parks_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='dues_parks_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='dues_roads_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='dues_roads_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='dues_sewer_cap_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='dues_sewer_cap_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='dues_sewer_trans_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='dues_sewer_trans_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='dues_storm_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicallot',
            name='dues_storm_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicalplat',
            name='calculation_note',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='historicalplat',
            name='non_sewer_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicalplat',
            name='sewer_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='dues_open_space_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='dues_open_space_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='dues_parks_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='dues_parks_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='dues_roads_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='dues_roads_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='dues_sewer_cap_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='dues_sewer_cap_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='dues_sewer_trans_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='dues_sewer_trans_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='dues_storm_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='dues_storm_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='plat',
            name='calculation_note',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='non_sewer_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='plat',
            name='sewer_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
