# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-16 18:39
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Count

def change_duplicates(apps, schema_editor):
    Lot = apps.get_model('plats', 'Lot')
    
    duplicate_lots = Lot.objects.values(
        'address_number', 'address_street', 'address_unit', 'address_direction'
    ).annotate(
        Count('id')
    ).order_by(
        'address_number', 'address_street'
    ).filter(
        id__count__gt=1
    )
    
    ignore_ids = []

    for dup in duplicate_lots:
        dup_lots = Lot.objects.filter(
            address_number=dup['address_number'],
            address_street=dup['address_street'],
            address_unit=dup['address_unit'],
            address_direction=dup['address_direction'],
        )
        
        ignore_ids.append(dup_lots.first().id)
        
        for lot in dup_lots:
            if lot.id in ignore_ids:
                pass
            else:
                ignore_ids.append(lot.id)
                lot.address_street = lot.address_street + ' DUPLICATE ' + str(lot.id)
                lot.address_full = lot.address_full + ' DUPLICATE '
                lot.save()

class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0004_auto_20201203_1441'),
    ]

    operations = [
        migrations.RunPython(
            change_duplicates,
            change_duplicates,
        ),
    ]
