# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-16 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0005_auto_20220216_1339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together=set([('address_number', 'address_street')]),
        ),
    ]
