# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0008_auto_20170717_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallot',
            name='address_zip',
            field=models.CharField(choices=[('40505', '40505'), ('40509', '40509'), ('40511', '40511'), ('40515', '40515'), ('40516', '40516')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lot',
            name='address_zip',
            field=models.CharField(choices=[('40505', '40505'), ('40509', '40509'), ('40511', '40511'), ('40515', '40515'), ('40516', '40516')], max_length=10),
        ),
    ]
