# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0010_auto_20170724_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplat',
            name='total_acreage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='plat',
            name='total_acreage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
