# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170731_1038'),
        ('plats', '0011_auto_20170724_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallot',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='historicalplat',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='lot',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lot_account', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='plat',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plat_account', to='accounts.Account'),
        ),
    ]
