# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0012_auto_20170731_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallot',
            name='address_zip',
            field=models.CharField(blank=True, choices=[('40505', '40505'), ('40509', '40509'), ('40511', '40511'), ('40515', '40515'), ('40516', '40516')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='address_zip',
            field=models.CharField(blank=True, choices=[('40505', '40505'), ('40509', '40509'), ('40511', '40511'), ('40515', '40515'), ('40516', '40516')], max_length=10, null=True),
        ),
    ]
