# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0013_auto_20170822_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplat',
            name='non_buildable_lots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plat',
            name='non_buildable_lots',
            field=models.IntegerField(default=0),
        ),
    ]
