# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0014_auto_20170829_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallot',
            name='address_state',
            field=models.CharField(choices=[('KY', 'Kentucky')], default='KY', max_length=50),
        ),
        migrations.AlterField(
            model_name='lot',
            name='address_state',
            field=models.CharField(choices=[('KY', 'Kentucky')], default='KY', max_length=50),
        ),
    ]
