# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0015_auto_20171005_1328'),
        ('plats', '0015_auto_20171006_1242'),
    ]

    operations = [
    ]
