# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0016_merge_20171006_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallot',
            name='alternative_address_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='alternative_address_street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='alternative_address_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='alternative_address_street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
