# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0018_auto_20171019_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplat',
            name='block',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplat',
            name='section',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='block',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='section',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
