# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0020_auto_20171107_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplat',
            name='calculation_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='calculation_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
