# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-20 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0021_auto_20171107_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallot',
            old_name='certificate_of_occupancy',
            new_name='certificate_of_occupancy_final',
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='certificate_of_occupancy',
            new_name='certificate_of_occupancy_final',
        ),
        migrations.AddField(
            model_name='historicallot',
            name='certificate_of_occupancy_conditional',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalplat',
            name='acreage_type',
            field=models.CharField(blank=True, choices=[('GROSS', 'gross'), ('NET', 'net')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalplat',
            name='amended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalplat',
            name='amended_parent_plat',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plats.Plat'),
        ),
        migrations.AddField(
            model_name='historicalplat',
            name='case_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalplat',
            name='right_of_way_acreage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalplat',
            name='signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='certificate_of_occupancy_conditional',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plat',
            name='acreage_type',
            field=models.CharField(blank=True, choices=[('GROSS', 'gross'), ('NET', 'net')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plat',
            name='amended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plat',
            name='amended_parent_plat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plat_amend', to='plats.Plat'),
        ),
        migrations.AddField(
            model_name='plat',
            name='case_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plat',
            name='right_of_way_acreage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='plat',
            name='signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculationworksheet',
            name='zone',
            field=models.CharField(choices=[('EAR-1', 'EAR-1'), ('EAR-1SRA', 'EAR-1SRA'), ('EAR-1SDAO', 'EAR-1 (Special Design Area Overlay)'), ('EAR-2', 'EAR-2'), ('EAR-2/TA', 'EAR-2 / TA'), ('EAR-3', 'EAR-3'), ('A-R', 'A-R'), ('B-5P', 'B-5P'), ('CC(RES)', 'CC(RES)'), ('CC(NONR)', 'CC(NONR)'), ('ED', 'ED')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcalculationworksheet',
            name='zone',
            field=models.CharField(choices=[('EAR-1', 'EAR-1'), ('EAR-1SRA', 'EAR-1SRA'), ('EAR-1SDAO', 'EAR-1 (Special Design Area Overlay)'), ('EAR-2', 'EAR-2'), ('EAR-2/TA', 'EAR-2 / TA'), ('EAR-3', 'EAR-3'), ('A-R', 'A-R'), ('B-5P', 'B-5P'), ('CC(RES)', 'CC(RES)'), ('CC(NONR)', 'CC(NONR)'), ('ED', 'ED')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalplatzone',
            name='zone',
            field=models.CharField(choices=[('EAR-1', 'EAR-1'), ('EAR-1SRA', 'EAR-1SRA'), ('EAR-1SDAO', 'EAR-1 (Special Design Area Overlay)'), ('EAR-2', 'EAR-2'), ('EAR-2/TA', 'EAR-2 / TA'), ('EAR-3', 'EAR-3'), ('A-R', 'A-R'), ('B-5P', 'B-5P'), ('CC(RES)', 'CC(RES)'), ('CC(NONR)', 'CC(NONR)'), ('ED', 'ED')], max_length=100),
        ),
        migrations.AlterField(
            model_name='platzone',
            name='zone',
            field=models.CharField(choices=[('EAR-1', 'EAR-1'), ('EAR-1SRA', 'EAR-1SRA'), ('EAR-1SDAO', 'EAR-1 (Special Design Area Overlay)'), ('EAR-2', 'EAR-2'), ('EAR-2/TA', 'EAR-2 / TA'), ('EAR-3', 'EAR-3'), ('A-R', 'A-R'), ('B-5P', 'B-5P'), ('CC(RES)', 'CC(RES)'), ('CC(NONR)', 'CC(NONR)'), ('ED', 'ED')], max_length=100),
        ),
    ]
