# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-13 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0023_auto_20180725_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallot',
            name='current_dues_open_space_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='current_dues_open_space_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='current_dues_parks_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='current_dues_parks_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='current_dues_roads_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='current_dues_roads_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='current_dues_sewer_cap_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='current_dues_sewer_cap_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='current_dues_sewer_trans_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='current_dues_sewer_trans_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='current_dues_storm_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='current_dues_storm_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicalplat',
            name='current_non_sewer_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicalplat',
            name='current_sewer_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='current_dues_open_space_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='current_dues_open_space_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='current_dues_parks_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='current_dues_parks_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='current_dues_roads_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='current_dues_roads_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='current_dues_sewer_cap_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='current_dues_sewer_cap_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='current_dues_sewer_trans_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='current_dues_sewer_trans_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='current_dues_storm_dev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='current_dues_storm_own',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='plat',
            name='current_non_sewer_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='plat',
            name='current_sewer_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
