# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcostestimate',
            old_name='admin_cont',
            new_name='admin_cost',
        ),
    ]
