# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170727_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='account',
            name='plat',
        ),
    ]
