# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170731_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='expansion_area',
            field=models.CharField(choices=[('EA-1', 'EA-1'), ('EA-2A', 'EA-2A'), ('EA-2B', 'EA-2B'), ('EA-2C', 'EA-2C'), ('EA-3', 'EA-3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalagreement',
            name='expansion_area',
            field=models.CharField(choices=[('EA-1', 'EA-1'), ('EA-2A', 'EA-2A'), ('EA-2B', 'EA-2B'), ('EA-2C', 'EA-2C'), ('EA-3', 'EA-3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='expansion_area',
            field=models.CharField(choices=[('EA-1', 'EA-1'), ('EA-2A', 'EA-2A'), ('EA-2B', 'EA-2B'), ('EA-2C', 'EA-2C'), ('EA-3', 'EA-3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='expansion_area',
            field=models.CharField(choices=[('EA-1', 'EA-1'), ('EA-2A', 'EA-2A'), ('EA-2B', 'EA-2B'), ('EA-2C', 'EA-2C'), ('EA-3', 'EA-3')], max_length=100),
        ),
    ]
