# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170802_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='project_category',
            field=models.CharField(choices=[('ROADS', 'Roads'), ('OPEN_SPACE', 'Open Space'), ('SEWER_CAP', 'Sewer Capacity'), ('SEWER_TRANS', 'Sewer Trans.'), ('PARK', 'Park'), ('STORM_WATER', 'Storm Water')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='project_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='project_type',
            field=models.CharField(choices=[('Roads', (('BOULVARD', 'Boulevard'), ('PARKWAY', 'Parkway'), ('TWO_LANE_BOULEVARD', 'Two-Lane Boulevard'), ('TWO_LANE_PARKWAY', 'Two-Lane Parkway'))), ('Sewer', (('SEWER_TRANSIMSSION', 'Sanitary sewer transmission'),)), ('Stormwater', (('STORMWATER', 'Stormwater'), ('LAND_AQUISITION', 'Land Aquisition'))), ('Parks', (('PARKS_AQUISITION', 'Parks Aquisition'),))], max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.CharField(choices=[('ROADS', 'Roads'), ('OPEN_SPACE', 'Open Space'), ('SEWER_CAP', 'Sewer Capacity'), ('SEWER_TRANS', 'Sewer Trans.'), ('PARK', 'Park'), ('STORM_WATER', 'Storm Water')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Roads', (('BOULVARD', 'Boulevard'), ('PARKWAY', 'Parkway'), ('TWO_LANE_BOULEVARD', 'Two-Lane Boulevard'), ('TWO_LANE_PARKWAY', 'Two-Lane Parkway'))), ('Sewer', (('SEWER_TRANSIMSSION', 'Sanitary sewer transmission'),)), ('Stormwater', (('STORMWATER', 'Stormwater'), ('LAND_AQUISITION', 'Land Aquisition'))), ('Parks', (('PARKS_AQUISITION', 'Parks Aquisition'),))], max_length=200),
        ),
    ]
