# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170819_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='project_category',
            field=models.CharField(choices=[('ROADS', 'Roads'), ('SEWER', 'Sanitary Sewer'), ('PARK', 'Park'), ('STORM_WATER', 'Storm Water')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.CharField(choices=[('ROADS', 'Roads'), ('SEWER', 'Sanitary Sewer'), ('PARK', 'Park'), ('STORM_WATER', 'Storm Water')], max_length=100),
        ),
    ]
