# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170819_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agreement_type',
            field=models.CharField(choices=[('MEMO', 'Memo'), ('RESOLUTION', 'Resolution')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalagreement',
            name='agreement_type',
            field=models.CharField(choices=[('MEMO', 'Memo'), ('RESOLUTION', 'Resolution')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='paid_by_type',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('OWNER', 'Home Owner')], max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_by_type',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('OWNER', 'Home Owner')], max_length=100),
        ),
    ]
