# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170819_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='project_type',
            field=models.CharField(choices=[('Roads', (('BOULEVARD', 'Boulevard'), ('PARKWAY', 'Parkway'), ('TWO_LANE_BOULEVARD', 'Two-Lane Boulevard'), ('TWO_LANE_PARKWAY', 'Two-Lane Parkway'))), ('Sewer', (('SEWER_TRANSMISSION', 'Sanitary sewer transmission'),)), ('Stormwater', (('STORMWATER', 'Stormwater'), ('LAND_AQUISITION', 'Land Aquisition'))), ('Parks', (('PARKS_AQUISITION', 'Parks Aquisition'),))], max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Roads', (('BOULEVARD', 'Boulevard'), ('PARKWAY', 'Parkway'), ('TWO_LANE_BOULEVARD', 'Two-Lane Boulevard'), ('TWO_LANE_PARKWAY', 'Two-Lane Parkway'))), ('Sewer', (('SEWER_TRANSMISSION', 'Sanitary sewer transmission'),)), ('Stormwater', (('STORMWATER', 'Stormwater'), ('LAND_AQUISITION', 'Land Aquisition'))), ('Parks', (('PARKS_AQUISITION', 'Parks Aquisition'),))], max_length=200),
        ),
    ]
