# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170823_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address_number',
            field=models.IntegerField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='address_street',
            field=models.CharField(default='State St', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='address_number',
            field=models.IntegerField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='address_street',
            field=models.CharField(default='State', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalprojectcostestimate',
            name='other_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcostestimate',
            name='other_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='entry_type',
            field=models.CharField(choices=[('NEW', 'New'), ('SELL', 'Sell'), ('TRANSFER', 'Transfer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_type',
            field=models.CharField(choices=[('MEMO', 'Memo'), ('RESOLUTION', 'Resolution'), ('OTHER', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalaccountledger',
            name='entry_type',
            field=models.CharField(choices=[('NEW', 'New'), ('SELL', 'Sell'), ('TRANSFER', 'Transfer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalagreement',
            name='agreement_type',
            field=models.CharField(choices=[('MEMO', 'Memo'), ('RESOLUTION', 'Resolution'), ('OTHER', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='paid_by_type',
            field=models.CharField(choices=[('BUILDER', 'Builder'), ('DEVELOPER', 'Developer'), ('OWNER', 'Home Owner')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='payment_type',
            field=models.CharField(choices=[('CHECK', 'Check'), ('CREDIT_CARD', 'Credit Card'), ('OTHER', 'Other')], default='check', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='project_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete'), ('CLOSED', 'Closed Out')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='project_type',
            field=models.CharField(choices=[('Roads', (('BOULEVARD', 'Boulevard'), ('PARKWAY', 'Parkway'), ('TWO_LANE_BOULEVARD', 'Two-Lane Boulevard'), ('TWO_LANE_PARKWAY', 'Two-Lane Parkway'))), ('Sewer', (('SEWER_TRANSIMSSION', 'Sanitary sewer transmission'), ('SEWER_OTHER', 'Other Sewer'))), ('Stormwater', (('STORMWATER', 'Stormwater'), ('LAND_AQUISITION', 'Land Aquisition'))), ('Parks', (('PARKS_AQUISITION', 'Parks Aquisition'),)), ('Other', (('OTHER_NON_SEWER', 'Other Non-Sewer'),))], max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_by_type',
            field=models.CharField(choices=[('BUILDER', 'Builder'), ('DEVELOPER', 'Developer'), ('OWNER', 'Home Owner')], max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CHECK', 'Check'), ('CREDIT_CARD', 'Credit Card'), ('OTHER', 'Other')], default='check', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete'), ('CLOSED', 'Closed Out')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Roads', (('BOULEVARD', 'Boulevard'), ('PARKWAY', 'Parkway'), ('TWO_LANE_BOULEVARD', 'Two-Lane Boulevard'), ('TWO_LANE_PARKWAY', 'Two-Lane Parkway'))), ('Sewer', (('SEWER_TRANSIMSSION', 'Sanitary sewer transmission'), ('SEWER_OTHER', 'Other Sewer'))), ('Stormwater', (('STORMWATER', 'Stormwater'), ('LAND_AQUISITION', 'Land Aquisition'))), ('Parks', (('PARKS_AQUISITION', 'Parks Aquisition'),)), ('Other', (('OTHER_NON_SEWER', 'Other Non-Sewer'),))], max_length=200),
        ),
    ]
