# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170826_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='project_type',
            field=models.CharField(choices=[('Roads', (('BOULEVARD', 'Boulevard'), ('PARKWAY', 'Parkway'), ('TWO_LANE_BOULEVARD', 'Two-Lane Boulevard'), ('TWO_LANE_PARKWAY', 'Two-Lane Parkway'))), ('Sewer', (('SEWER_TRANSMISSION', 'Sanitary sewer transmission'), ('SEWER_OTHER', 'Other Sewer'))), ('Stormwater', (('STORMWATER', 'Stormwater'), ('LAND_AQUISITION', 'Land Aquisition'))), ('Parks', (('PARKS_AQUISITION', 'Parks Aquisition'),)), ('Other', (('OTHER_NON_SEWER', 'Other Non-Sewer'),))], max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Roads', (('BOULEVARD', 'Boulevard'), ('PARKWAY', 'Parkway'), ('TWO_LANE_BOULEVARD', 'Two-Lane Boulevard'), ('TWO_LANE_PARKWAY', 'Two-Lane Parkway'))), ('Sewer', (('SEWER_TRANSMISSION', 'Sanitary sewer transmission'), ('SEWER_OTHER', 'Other Sewer'))), ('Stormwater', (('STORMWATER', 'Stormwater'), ('LAND_AQUISITION', 'Land Aquisition'))), ('Parks', (('PARKS_AQUISITION', 'Parks Aquisition'),)), ('Other', (('OTHER_NON_SEWER', 'Other Non-Sewer'),))], max_length=200),
        ),
    ]
