# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170901_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='project_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('CLOSED', 'Closed Out')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('CLOSED', 'Closed Out')], max_length=100),
        ),
    ]
