# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_auto_20170901_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_supervisor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='entry_type',
            field=models.CharField(choices=[('NEW', 'New Credits'), ('USE', 'Use Credits'), ('TRANSFER', 'Transfer Credits')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalaccountledger',
            name='entry_type',
            field=models.CharField(choices=[('NEW', 'New Credits'), ('USE', 'Use Credits'), ('TRANSFER', 'Transfer Credits')], max_length=100),
        ),
    ]
