# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20170901_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountledger',
            name='entry_type',
            field=models.CharField(choices=[('NEW', 'New Credits'), ('USE', 'Use Credits'), ('TRANSFER', 'Transfer Credits')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalaccountledger',
            name='entry_type',
            field=models.CharField(choices=[('NEW', 'New Credits'), ('USE', 'Use Credits'), ('TRANSFER', 'Transfer Credits')], max_length=100),
        ),
    ]
