# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20171013_0907'),
        ('accounts', '0017_auto_20171012_1627'),
        ('accounts', '0019_auto_20171013_0857'),
    ]

    operations = [
    ]
