# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_20171013_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='check_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='check_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
