# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-06 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20180827_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountledger',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='resolution_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalaccountledger',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalagreement',
            name='resolution_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectcostestimate',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_cost_estimate', to='accounts.Project'),
        ),
    ]
