// API ACTIONS
export const ACCELA_API_CALL = 'ACCELA_API_CALL';
export const ACCELA_API_CALL_SUCCESS = 'ACCELA_API_CALL_SUCCESS';
export const ACCELA_API_CALL_ERROR = 'ACCELA_API_CALL_ERROR';
export const ACCELA_API_CALL_VALIDATION_ERROR = 'ACCELA_API_CALL_VALIDATION_ERROR';

// API CALLS TO ACCELA DATABASE
export const GET_ACCELA = 'GET_ACCELA';
export const GET_ACCELA_ID = 'GET_ACCELA_ID';
export const PUT_ACCELA_ID = 'PUT_ACCELA_ID';
