export const BASE_URL = '/api';

export const ME = 'ME';

export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const PASSWORD = 'PASSWORD';
export const SEND_USERNAME = 'SEND_USERNAME';
export const LOGOUT = 'LOGOUT';

export const GET_SUBDIVISIONS = 'GET_SUBDIVISIONS';
export const GET_SUBDIVISION_ID = 'GET_SUBDIVISION_ID';
export const GET_SUBDIVISION_QUERY = 'GET_SUBDIVISION_QUERY';
export const POST_SUBDIVISION = 'POST_SUBDIVISION';
export const PUT_SUBDIVISIOIN = 'PUT_SUBDIVISIOIN';

export const GET_PLATS = 'GET_PLATS';
export const GET_PLAT_ID = 'GET_PLAT_ID';
export const GET_PLAT_QUERY = 'GET_PLAT_QUERY';
export const POST_PLAT = 'POST_PLAT';
export const PUT_PLAT = 'PUT_PLAT';

export const GET_PLAT_ZONES = 'GET_PLAT_ZONES';
export const GET_PLAT_ZONE_ID = 'GET_PLAT_ZONE_ID';
export const POST_PLAT_ZONE = 'POST_PLAT_ZONE';
export const PUT_PLAT_ZONE = 'PUT_PLAT_ZONE';
export const PUT_PLAT_ZONE_DUES = 'PUT_PLAT_ZONE_DUES';

export const GET_LOTS = 'GET_LOTS';
export const GET_LOT_ID = 'GET_LOT_ID';
export const GET_LOT_QUERY = 'GET_LOT_QUERY';
export const GET_PLAT_LOTS = 'GET_PLAT_LOTS';
export const POST_LOT = 'POST_LOT';
export const PUT_LOT = 'PUT_LOT';

export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const GET_ACCOUNT_ID = 'GET_ACCOUNT_ID';
export const GET_ACCOUNT_QUERY = 'GET_ACCOUNT_QUERY';
export const POST_ACCOUNT = 'POST_ACCOUNT';
export const PUT_ACCOUNT = 'PUT_ACCOUNT';

export const GET_NOTE_CONTENT = 'GET_NOTE_CONTENT';
export const POST_NOTE = 'POST_NOTE';

export const GET_AGREEMENTS = 'GET_AGREEMENTS';
export const GET_AGREEMENT_ID = 'GET_AGREEMENT_ID';
export const GET_AGREEMENT_QUERY = 'GET_AGREEMENT_QUERY';
export const GET_ACCOUNT_AGREEMENTS = 'GET_ACCOUNT_AGREEMENTS';
export const POST_AGREEMENT = 'POST_AGREEMENT';
export const PUT_AGREEMENT = 'PUT_AGREEMENT';

export const GET_PAYMENTS = 'GET_PAYMENTS';
export const GET_PAYMENT_ID = 'GET_PAYMENT_ID';
export const GET_PAYMENT_QUERY = 'GET_PAYMENT_QUERY';
export const GET_LOT_PAYMENTS = 'GET_LOT_PAYMENTS';
export const GET_ACCOUNT_PAYMENTS = 'GET_ACCOUNT_PAYMENTS';
export const GET_AGREEMENT_PAYMENTS = 'GET_AGREEMENT_PAYMENTS';
export const POST_PAYMENT = 'POST_PAYMENT';
export const PUT_PAYMENT = 'PUT_PAYMENT';

export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT_ID = 'GET_PROJECT_ID';
export const GET_PROJECT_QUERY = 'GET_PROJECT_QUERY';
export const GET_AGREEMENT_PROJECTS = 'GET_AGREEMENT_PROJECTS';
export const POST_PROJECT = 'POST_PROJECT';
export const PUT_PROJECT = 'PUT_PROJECT';

export const GET_PROJECT_COSTS = 'GET_PROJECT_COSTS';
export const GET_PROJECT_COST_ID = 'GET_PROJECT_COST_ID';
export const GET_PROJECT_COST_QUERY = 'GET_PROJECT_COST_QUERY';
export const POST_PROJECT_COST = 'POST_PROJECT_COST';
export const PUT_PROJECT_COST = 'PUT_PROJECT_COST';

export const GET_ACCOUNT_LEDGERS = 'GET_ACCOUNT_LEDGERS';
export const GET_ACCOUNT_LEDGER_ID = 'GET_ACCOUNT_LEDGER_ID';
export const GET_ACCOUNT_LEDGER_QUERY = 'GET_ACCOUNT_LEDGER_QUERY';
export const GET_LOT_ACCOUNT_LEDGERS = 'GET_LOT_ACCOUNT_LEDGERS';
export const GET_ACCOUNT_ACCOUNT_LEDGERS = 'GET_ACCOUNT_ACCOUNT_LEDGERS';
export const GET_AGREEMENT_ACCOUNT_LEDGERS = 'GET_AGREEMENT_ACCOUNT_LEDGERS';
export const POST_ACCOUNT_LEDGER = 'POST_ACCOUNT_LEDGER';
export const PUT_ACCOUNT_LEDGER = 'PUT_ACCOUNT_LEDGER';
