# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20170629_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
