# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notes', '0008_auto_20170726_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=notes.models.model_directory_path)),
                ('file_object_id', models.PositiveIntegerField()),
                ('file_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
