# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_fileuploads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUploads',
            new_name='FileUpload',
        ),
    ]
