# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20170809_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
