# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_fileupload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
