# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_auto_20171101_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalratetable',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ratetable',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
