# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_auto_20171101_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalratetable',
            name='end_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratetable',
            name='end_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
