# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_auto_20171102_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrate',
            name='zone',
            field=models.CharField(choices=[('EAR-1', 'EAR-1'), ('EAR-1SRA', 'EAR-1SRA'), ('EAR-1SDAO', 'EAR-1 (Special Design Area Overlay)'), ('EAR-2', 'EAR-2'), ('EAR-2/TA', 'EAR-2 / TA'), ('EAR-3', 'EAR-3'), ('A-R', 'A-R'), ('B-5P', 'B-5P'), ('CC(RES)', 'CC(RES)'), ('CC(NONR)', 'CC(NONR)'), ('ED', 'ED')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rate',
            name='zone',
            field=models.CharField(choices=[('EAR-1', 'EAR-1'), ('EAR-1SRA', 'EAR-1SRA'), ('EAR-1SDAO', 'EAR-1 (Special Design Area Overlay)'), ('EAR-2', 'EAR-2'), ('EAR-2/TA', 'EAR-2 / TA'), ('EAR-3', 'EAR-3'), ('A-R', 'A-R'), ('B-5P', 'B-5P'), ('CC(RES)', 'CC(RES)'), ('CC(NONR)', 'CC(NONR)'), ('ED', 'ED')], max_length=100),
        ),
    ]
