# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-07 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_auto_20180807_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrate',
            name='expansion_area',
            field=models.CharField(choices=[('EA-1', 'EA-1'), ('EA-2A', 'EA-2A'), ('EA-2B', 'EA-2B'), ('EA-2A / 2B', 'EA-2A / 2B'), ('EA-2C', 'EA-2C'), ('EA-3', 'EA-3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rate',
            name='expansion_area',
            field=models.CharField(choices=[('EA-1', 'EA-1'), ('EA-2A', 'EA-2A'), ('EA-2B', 'EA-2B'), ('EA-2A / 2B', 'EA-2A / 2B'), ('EA-2C', 'EA-2C'), ('EA-3', 'EA-3')], max_length=100),
        ),
    ]
